.TH "ExporterHTML" 3 "Thu Mar 23 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExporterHTML \- \fBExporterHTML\fP child klasse die de output van gegevens naar een html-bestand behandelt\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exporter\&.h>\fP
.PP
Inherits \fBExporter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBwrite\fP (std::string &output, std::ostream &os)"
.br
.RI "Stuur de output string naar de output stream\&. "
.ti -1c
.RI "virtual void \fBfinish\fP (std::ostream &os)"
.br
.RI "Stuurt de nodige informatie naar de output stream om het document correct af te sluiten\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBExporterHTML\fP child klasse die de output van gegevens naar een html-bestand behandelt\&. 
.SH "Member Function Documentation"
.PP 
.SS "void ExporterHTML::finish (std::ostream & os)\fC [virtual]\fP"

.PP
Stuurt de nodige informatie naar de output stream om het document correct af te sluiten\&. 
.PP
\fBParameters:\fP
.RS 4
\fIos\fP De stream waar de output naar gestuurd zal worden\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Exporter was niet geinitialiseerd bij de aanroep van finish\&.'); 
.PP
REQUIRE(documentStarted, 'Document was niet aangemaakt voor de aanroep van finish\&.'); 
.RE
.PP

.PP
Reimplemented from \fBExporter\fP\&.
.SS "void ExporterHTML::write (std::string & output, std::ostream & os)\fC [virtual]\fP"

.PP
Stuur de output string naar de output stream\&. 
.PP
\fBParameters:\fP
.RS 4
\fIoutput\fP De string die naar de output gestuurd moet worden\&. 
.br
\fIos\fP De stream waar de output naar gestuurd zal worden\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Exporter was niet geinitialiseerd bij de aanroep van write\&.'); 
.RE
.PP
\fBPostcondition:\fP
.RS 4
ENSURE(documentStarted, 'Document was niet aangemaakt bij de aanroep van write\&.'); 
.RE
.PP

.PP
Reimplemented from \fBExporter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
