.TH "ExporterHTML" 3 "Thu Mar 16 2017" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExporterHTML \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exporter\&.h>\fP
.PP
Inherits \fBExporter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBwrite\fP (std::string &output, std::ostream &os)"
.br
.RI "\fIStuur de output string naar de output stream\&. \fP"
.ti -1c
.RI "virtual void \fBfinish\fP (std::ostream &os)"
.br
.RI "\fIStuurt de nodige informatie naar de output stream om het document correct af te sluiten\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "void ExporterHTML::finish (std::ostream & os)\fC [virtual]\fP"

.PP
Stuurt de nodige informatie naar de output stream om het document correct af te sluiten\&. 
.PP
\fBParameters:\fP
.RS 4
\fIos\fP De stream waar de output naar gestuurd zal worden\&.
.RE
.PP
REQUIRE(this->\fBproperlyInitialised()\fP, 'Exporter was niet geinitialiseerd bij de aanroep van finish\&.');
.br
REQUIRE(documentStarted, 'Document was niet aangemaakt voor de aanroep van finish\&.');
.br

.PP
Reimplemented from \fBExporter\fP\&.
.SS "void ExporterHTML::write (std::string & output, std::ostream & os)\fC [virtual]\fP"

.PP
Stuur de output string naar de output stream\&. 
.PP
\fBParameters:\fP
.RS 4
\fIoutput\fP De string die naar de output gestuurd moet worden\&. 
.br
\fIos\fP De stream waar de output naar gestuurd zal worden\&.
.RE
.PP
REQUIRE(this->\fBproperlyInitialised()\fP, 'Exporter was niet geinitialiseerd bij de aanroep van write\&.');
.br
ENSURE(documentStarted, 'Document was niet aangemaakt bij de aanroep van write\&.');
.br

.PP
Reimplemented from \fBExporter\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
