.TH "/home/sergio/EclipseProjects/SoftEng/src/Exporter.cpp" 3 "Thu Mar 9 2017" "SoftEng" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sergio/EclipseProjects/SoftEng/src/Exporter.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'Exporter\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for SoftEng from the source code\&.
