.TH "ExporterTXT" 3 "Thu Mar 9 2017" "SoftEng" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExporterTXT
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exporter\&.h>\fP
.PP
Inherits \fBExporter\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for SoftEng from the source code\&.
