.TH "Exporter" 3 "Wed Mar 22 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Exporter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exporter\&.h>\fP
.PP
Inherited by \fBExporterCLI\fP, \fBExporterHTML\fP, and \fBExporterTXT\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExporter\fP ()"
.br
.ti -1c
.RI "virtual bool \fBproperlyInitialised\fP () const "
.br
.RI "\fIKijk na of de constructor in de juiste staat geeindigd is\&. \fP"
.ti -1c
.RI "virtual void \fBwrite\fP (std::string &output, std::ostream &os)"
.br
.RI "\fIStuur de output string naar de output stream\&. \fP"
.ti -1c
.RI "virtual void \fBfinish\fP (std::ostream &os)"
.br
.RI "\fIStuurt de nodige informatie naar de output stream om het document correct af te sluiten\&. \fP"
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "bool \fBdocumentStarted\fP"
.br
.ti -1c
.RI "\fBExporter\fP * \fBinitCheck\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Exporter::Exporter ()"

.SH "Member Function Documentation"
.PP 
.SS "void Exporter::finish (std::ostream & os)\fC [virtual]\fP"

.PP
Stuurt de nodige informatie naar de output stream om het document correct af te sluiten\&. 
.PP
\fBParameters:\fP
.RS 4
\fIos\fP De stream waar de output naar gestuurd zal worden\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Exporter was niet geinitialiseerd bij de aanroep van finish\&.'); 
.PP
REQUIRE(documentStarted, 'Document was niet aangemaakt voor de aanroep van finish\&.'); 
.RE
.PP

.PP
Reimplemented in \fBExporterHTML\fP\&.
.SS "bool Exporter::properlyInitialised () const\fC [virtual]\fP"

.PP
Kijk na of de constructor in de juiste staat geeindigd is\&. 
.PP
\fBReturns:\fP
.RS 4
Boolean die aangeeft of het object juist geinitialiseerd is\&. 
.RE
.PP

.SS "void Exporter::write (std::string & output, std::ostream & os)\fC [virtual]\fP"

.PP
Stuur de output string naar de output stream\&. 
.PP
\fBParameters:\fP
.RS 4
\fIoutput\fP De string die naar de output gestuurd moet worden\&. 
.br
\fIos\fP De stream waar de output naar gestuurd zal worden\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Exporter was niet geinitialiseerd bij de aanroep van write\&.'); 
.RE
.PP
\fBPostcondition:\fP
.RS 4
ENSURE(documentStarted, 'Document was niet aangemaakt bij de aanroep van write\&.'); 
.RE
.PP

.PP
Reimplemented in \fBExporterHTML\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Exporter::documentStarted\fC [protected]\fP"

.SS "\fBExporter\fP* Exporter::initCheck\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
