.TH "ExporterTXT" 3 "Thu Mar 23 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ExporterTXT \- \fBExporterTXT\fP child klasse die de output van gegevens naar een txt-bestand behandelt\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exporter\&.h>\fP
.PP
Inherits \fBExporter\fP\&.
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBExporterTXT\fP child klasse die de output van gegevens naar een txt-bestand behandelt\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
