.TH "/home/jonathan/Desktop/Project Software Engineering/Metronet/PSE/src/main.cpp" 3 "Wed Mar 22 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jonathan/Desktop/Project Software Engineering/Metronet/PSE/src/main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include 'Metronet\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, const char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, const char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
