.TH "/home/sergio/EclipseProjects/SoftEng/src/main.cpp" 3 "Thu Mar 9 2017" "SoftEng" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sergio/EclipseProjects/SoftEng/src/main.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'Metronet\&.h'\fP
.br
\fC#include 'Parser\&.h'\fP
.br
\fC#include 'Exporter\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for SoftEng from the source code\&.
