.TH "Metronet" 3 "Wed Mar 22 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Metronet \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Metronet\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMetronet\fP ()"
.br
.ti -1c
.RI "\fBMetronet\fP (\fBExporter\fP *exp)"
.br
.ti -1c
.RI "virtual \fB~Metronet\fP ()"
.br
.ti -1c
.RI "\fBMetronet\fP & \fBoperator=\fP (const \fBMetronet\fP &rhs)"
.br
.ti -1c
.RI "bool \fBproperlyInitialised\fP ()"
.br
.RI "\fIKijk na of de constructor in de juiste staat geeindigd is\&. \fP"
.ti -1c
.RI "\fBSuccessEnum\fP \fBsetup\fP (std::string filename, std::ostream &os)"
.br
.RI "\fIVerwerkt het XML-bestand\&. \fP"
.ti -1c
.RI "std::map< std::string, \fBStation\fP * > \fBgetStations\fP ()"
.br
.RI "\fIGeeft alle stations in het metronet terug\&. \fP"
.ti -1c
.RI "std::map< int, \fBTram\fP * > & \fBgetTrams\fP ()"
.br
.RI "\fIGeeft alle trams in het metronet terug\&. \fP"
.ti -1c
.RI "void \fBaddStation\fP (\fBStation\fP *station)"
.br
.RI "\fIVoegt station toe aan metronet\&. \fP"
.ti -1c
.RI "void \fBaddTram\fP (\fBTram\fP *tram)"
.br
.RI "\fIVoegt tram toe aan metronet\&. \fP"
.ti -1c
.RI "void \fBaddSpoor\fP (int spoor)"
.br
.RI "\fIVoegt spoor toe aan metronet\&. \fP"
.ti -1c
.RI "bool \fBcheckConsistent\fP (std::ostream &os)"
.br
.RI "\fIKijkt na of het metronet consistent is\&. \fP"
.ti -1c
.RI "void \fBprintMetronet\fP (std::ostream &os)"
.br
.RI "\fIPrint het hele metronet\&. \fP"
.ti -1c
.RI "bool \fBopstappenAfstappen\fP (std::string station, std::ostream &os)"
.br
.RI "\fIBehandelt het opstappen en afstappen van passagiers\&. \fP"
.ti -1c
.RI "void \fBrondrijden\fP (std::ostream &os)"
.br
.RI "\fIEmuleert het rondrijden van trams\&. \fP"
.ti -1c
.RI "void \fBreset\fP ()"
.br
.RI "\fIReset heel het systeem\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Metronet::Metronet ()"

.SS "Metronet::Metronet (\fBExporter\fP * exp)"

.SS "Metronet::~Metronet ()\fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Metronet::addSpoor (int spoor)"

.PP
Voegt spoor toe aan metronet\&. 
.PP
\fBParameters:\fP
.RS 4
\fIspoor\fP Het spoor dat toegevoegd zal worden\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Metronet was niet geinitialiseerd bij de aanroep van addSpoor\&.'); 
.RE
.PP
\fBPostcondition:\fP
.RS 4
ENSURE(sporen[sporen\&.size() - 1] == spoor), 'Spoor was niet toegevoegd bij de aanroep van addSpoor\&.'); 
.RE
.PP

.SS "void Metronet::addStation (\fBStation\fP * station)"

.PP
Voegt station toe aan metronet\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstation\fP Het station dat toegevoegd zal worden\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Metronet was niet geinitialiseerd bij de aanroep van addStation\&.'); 
.PP
REQUIRE(station->\fBproperlyInitialised()\fP, 'Station was niet geinitialiseerd bij de aanroep van addStation\&.'); 
.RE
.PP
\fBPostcondition:\fP
.RS 4
ENSURE((stations\&.find(station->getNaam()) != stations\&.end()), 'Station was niet toegevoegd bij de aanroep van addStation\&.'); 
.RE
.PP

.SS "void Metronet::addTram (\fBTram\fP * tram)"

.PP
Voegt tram toe aan metronet\&. 
.PP
\fBParameters:\fP
.RS 4
\fItram\fP De tram die toegevoegd zal worden\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Metronet was niet geinitialiseerd bij de aanroep van addTram\&.'); 
.PP
REQUIRE(tram->\fBproperlyInitialised()\fP, 'Tram was niet geinitialiseerd bij de aanroep van addTram\&.'); 
.RE
.PP
\fBPostcondition:\fP
.RS 4
ENSURE(trams\&.find(tram->getSpoor()) != trams\&.end()), 'Tram was niet toegevoegd bij de aanroep van addTram\&.'); 
.RE
.PP

.SS "bool Metronet::checkConsistent (std::ostream & os)"

.PP
Kijkt na of het metronet consistent is\&. 
.PP
\fBParameters:\fP
.RS 4
\fIexp\fP De exporter die de output zal behandelen\&. 
.br
\fIos\fP De stream waar de output naar gestuurd zal worden\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
Boolean die aangeeft of het \fBMetronet\fP consistent is\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Metronet was niet geinitialiseerd bij de aanroep van checkConsistent\&.'); 
.RE
.PP

.SS "std::map< std::string, \fBStation\fP * > Metronet::getStations ()"

.PP
Geeft alle stations in het metronet terug\&. 
.PP
\fBReturns:\fP
.RS 4
Map met stations in het metronet\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Metronet was niet geinitialiseerd bij de aanroep van getStations\&.'); 
.RE
.PP

.SS "std::map< int, \fBTram\fP * > & Metronet::getTrams ()"

.PP
Geeft alle trams in het metronet terug\&. 
.PP
\fBReturns:\fP
.RS 4
Map met trams in het metronet\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Metronet was niet geinitialiseerd bij de aanroep van getTrams\&.'); 
.RE
.PP

.SS "\fBMetronet\fP & Metronet::operator= (const \fBMetronet\fP & rhs)"

.SS "bool Metronet::opstappenAfstappen (std::string station, std::ostream & os)"

.PP
Behandelt het opstappen en afstappen van passagiers\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstation\fP Het station waar mensen opstappen en afstappen\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Metronet was niet geinitialiseerd bij aanroep van opstappenAfstappen\&.'); 
.PP
REQUIRE((stations\&.find(station) != stations\&.end()), 'Station bestaat niet in het metronet\&.'); 
.PP
REQUIRE(stations[station]->\fBproperlyInitialised()\fP, 'Station was niet geinitialiseerd bij aanroep van opstappenAfstappen\&.'); 
.RE
.PP

.SS "void Metronet::printMetronet (std::ostream & os)"

.PP
Print het hele metronet\&. 
.PP
\fBParameters:\fP
.RS 4
\fIexp\fP De exporter die gebruikt moet worden 
.br
\fIos\fP De stream waar de output naar gestuurd moet worden 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Metronet was niet geinitialiseerd bij aanroep van printMetronet\&.'); 
.RE
.PP

.SS "bool Metronet::properlyInitialised ()"

.PP
Kijk na of de constructor in de juiste staat geeindigd is\&. 
.PP
\fBReturns:\fP
.RS 4
Boolean die aangeeft of het object juist geinitialiseerd is\&. 
.RE
.PP

.SS "void Metronet::reset ()"

.PP
Reset heel het systeem\&. 
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Metronet was niet geinitialiseerd bij aanroep van reset\&.'); 
.RE
.PP

.SS "void Metronet::rondrijden (std::ostream & os)"

.PP
Emuleert het rondrijden van trams\&. 
.PP
\fBParameters:\fP
.RS 4
\fIos\fP De stream waar de output naar gestuurd moet worden 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Metronet was niet geinitialiseerd bij aanroep van rondrijden\&.'); 
.RE
.PP

.SS "\fBSuccessEnum\fP Metronet::setup (std::string filename, std::ostream & os)"

.PP
Verwerkt het XML-bestand\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfilename\fP De naam van het XML-bestand\&. 
.br
\fIos\fP De stream waarnaar de output geschreven wordt (nodig voor de exporter)\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->properlyInitialised, 'Het metronet was niet geinitialiseerd bij het aanroepen van setupStations\&.'); 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
