.TH "/home/sergio/CLionProjects/SoftEng/src/MetronetOutputTest.cpp" 3 "Thu Mar 23 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sergio/CLionProjects/SoftEng/src/MetronetOutputTest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'MetronetOutputTest\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetOutputTest\fP, OutputLegalSystemsTxt)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetOutputTest\fP, OutputIllegalSystemsTxt)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetOutputTest\fP, OutputIncorrectSystemsTxt)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetOutputTest\fP, OutputSyntaxErrorSystemsTxt)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetOutputTest\fP, OutputLegalSystemsHtml)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetOutputTest\fP, OutputIllegalSystemsHtml)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetOutputTest\fP, OutputIncorrectSystemsHtml)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetOutputTest\fP, OutputSyntaxErrorSystemsHtml)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST_F (\fBMetronetOutputTest\fP, OutputLegalSystemsTxt)"

.SS "TEST_F (\fBMetronetOutputTest\fP, OutputIllegalSystemsTxt)"

.SS "TEST_F (\fBMetronetOutputTest\fP, OutputIncorrectSystemsTxt)"

.SS "TEST_F (\fBMetronetOutputTest\fP, OutputSyntaxErrorSystemsTxt)"

.SS "TEST_F (\fBMetronetOutputTest\fP, OutputLegalSystemsHtml)"

.SS "TEST_F (\fBMetronetOutputTest\fP, OutputIllegalSystemsHtml)"

.SS "TEST_F (\fBMetronetOutputTest\fP, OutputIncorrectSystemsHtml)"

.SS "TEST_F (\fBMetronetOutputTest\fP, OutputSyntaxErrorSystemsHtml)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
