.TH "/home/jonathan/Desktop/Project Software Engineering/Metronet/PSE/src/MetronetUtils.h" 3 "Wed Mar 22 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jonathan/Desktop/Project Software Engineering/Metronet/PSE/src/MetronetUtils.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBDirectoryExists\fP (const std::string dirname)"
.br
.ti -1c
.RI "bool \fBFileExists\fP (const std::string dirname)"
.br
.ti -1c
.RI "bool \fBFileIsEmpty\fP (const std::string filename)"
.br
.ti -1c
.RI "bool \fBFileCompare\fP (const std::string leftFileName, const std::string rightFileName)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned int \fBTESTS_LEGAL\fP = 4"
.br
.ti -1c
.RI "const unsigned int \fBTESTS_ILLEGAL\fP = 9"
.br
.ti -1c
.RI "const unsigned int \fBTESTS_INCORRECT\fP = 4"
.br
.ti -1c
.RI "const unsigned int \fBTESTS_SYNTAX\fP = 3"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool DirectoryExists (const std::string dirname)"

.SS "bool FileCompare (const std::string leftFileName, const std::string rightFileName)"

.SS "bool FileExists (const std::string dirname)"

.SS "bool FileIsEmpty (const std::string filename)"

.SH "Variable Documentation"
.PP 
.SS "const unsigned int TESTS_ILLEGAL = 9"

.SS "const unsigned int TESTS_INCORRECT = 4"

.SS "const unsigned int TESTS_LEGAL = 4"

.SS "const unsigned int TESTS_SYNTAX = 3"

.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
