.TH "/home/sergio/CLionProjects/SoftEng/src/MetronetDomainTest.cpp" 3 "Thu Mar 23 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sergio/CLionProjects/SoftEng/src/MetronetDomainTest.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'MetronetDomainTest\&.h'\fP
.br
\fC#include <limits>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, ProperlyInitialised)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, ExporterTest)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, ExporterCLITest)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, ExporterTXTTest)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, ExporterHTMLTest)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, CheckConsistent)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, VerplaatsTram)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, OpstappenAfstappenNormaal)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, OpstappenAfstappenOverflow)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, OpstappenAfstappenNegative)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, addTram)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, addStation)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, rondrijden)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST_F (\fBMetronetDomainTest\fP, ProperlyInitialised)"

.SS "TEST_F (\fBMetronetDomainTest\fP, ExporterTest)"

.SS "TEST_F (\fBMetronetDomainTest\fP, ExporterCLITest)"

.SS "TEST_F (\fBMetronetDomainTest\fP, ExporterTXTTest)"

.SS "TEST_F (\fBMetronetDomainTest\fP, ExporterHTMLTest)"

.SS "TEST_F (\fBMetronetDomainTest\fP, CheckConsistent)"

.SS "TEST_F (\fBMetronetDomainTest\fP, VerplaatsTram)"

.SS "TEST_F (\fBMetronetDomainTest\fP, OpstappenAfstappenNormaal)"

.SS "TEST_F (\fBMetronetDomainTest\fP, OpstappenAfstappenOverflow)"

.SS "TEST_F (\fBMetronetDomainTest\fP, OpstappenAfstappenNegative)"

.SS "TEST_F (\fBMetronetDomainTest\fP, addTram)"

.SS "TEST_F (\fBMetronetDomainTest\fP, addStation)"

.SS "TEST_F (\fBMetronetDomainTest\fP, rondrijden)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
