.TH "/home/sergio/CLionProjects/SoftEng/src/MetronetDomainTest.h" 3 "Thu Mar 23 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sergio/CLionProjects/SoftEng/src/MetronetDomainTest.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <gtest/gtest\&.h>\fP
.br
\fC#include <sys/stat\&.h>\fP
.br
\fC#include 'MetronetUtils\&.h'\fP
.br
\fC#include 'Metronet\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMetronetDomainTest\fP"
.br
.RI "\fBMetronetDomainTest\fP klasse die domein tests behandelt\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
