.TH "/home/sergio/CLionProjects/SoftEng/src/Metronet.h" 3 "Thu Mar 23 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sergio/CLionProjects/SoftEng/src/Metronet.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <map>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'tinyxml\&.h'\fP
.br
\fC#include 'tinystr\&.h'\fP
.br
\fC#include 'Station\&.h'\fP
.br
\fC#include 'Tram\&.h'\fP
.br
\fC#include 'Exporter\&.h'\fP
.br
\fC#include 'DesignByContract\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMetronet\fP"
.br
.RI "\fBMetronet\fP klasse die XML bestanden inleest, de consistentie hiervan nagaat en Trams en Stations bijhoudt\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSuccessEnum\fP { \fBSuccess\fP, \fBPartialImport\fP, \fBBadImport\fP }
.RI "Enum gebruikt om te bepalen of bestand correct, partieel of fout is ingelezen\&. ""
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBSuccessEnum\fP"

.PP
Enum gebruikt om te bepalen of bestand correct, partieel of fout is ingelezen\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISuccess \fP\fP
.TP
\fB\fIPartialImport \fP\fP
.TP
\fB\fIBadImport \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
