.TH "/home/jonathan/Desktop/Project Software Engineering/Metronet/PSE/src/MetronetDomainTest.cpp" 3 "Wed Mar 22 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jonathan/Desktop/Project Software Engineering/Metronet/PSE/src/MetronetDomainTest.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'MetronetDomainTest\&.h'\fP
.br
\fC#include <limits>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, ProperlyInitialised)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, CheckConsistent)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, VerplaatsTram)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, OpstappenAfstappenNormaal)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, OpstappenAfstappenOverflow)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, OpstappenAfstappenNegative)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, addTram)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, addStation)"
.br
.ti -1c
.RI "\fBTEST_F\fP (\fBMetronetDomainTest\fP, rondrijden)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned int \fBTESTS_CONSISTENT\fP = 2"
.br
.ti -1c
.RI "const unsigned int \fBTESTS_INCONSISTENT\fP = 3"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "TEST_F (\fBMetronetDomainTest\fP, ProperlyInitialised)"

.SS "TEST_F (\fBMetronetDomainTest\fP, CheckConsistent)"

.SS "TEST_F (\fBMetronetDomainTest\fP, VerplaatsTram)"

.SS "TEST_F (\fBMetronetDomainTest\fP, OpstappenAfstappenNormaal)"

.SS "TEST_F (\fBMetronetDomainTest\fP, OpstappenAfstappenOverflow)"

.SS "TEST_F (\fBMetronetDomainTest\fP, OpstappenAfstappenNegative)"

.SS "TEST_F (\fBMetronetDomainTest\fP, addTram)"

.SS "TEST_F (\fBMetronetDomainTest\fP, addStation)"

.SS "TEST_F (\fBMetronetDomainTest\fP, rondrijden)"

.SH "Variable Documentation"
.PP 
.SS "const unsigned int TESTS_CONSISTENT = 2"

.SS "const unsigned int TESTS_INCONSISTENT = 3"

.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
