.TH "Parser" 3 "Thu Mar 16 2017" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Parser \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Parser\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParser\fP ()"
.br
.ti -1c
.RI "\fBParser\fP (\fBExporter\fP *exp)"
.br
.ti -1c
.RI "bool \fBsetup\fP (\fBMetronet\fP &metro, std::string filename, std::ostream &os)"
.br
.RI "\fIVerwerkt het XML-bestand en zet het metronet op\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Parser::Parser ()"

.SS "Parser::Parser (\fBExporter\fP * exp)"

.SH "Member Function Documentation"
.PP 
.SS "bool Parser::setup (\fBMetronet\fP & metro, std::string filename, std::ostream & os)"

.PP
Verwerkt het XML-bestand en zet het metronet op\&. 
.PP
\fBParameters:\fP
.RS 4
\fImetro\fP Het metronet (referentie) dat aangepast moet worden\&. 
.br
\fIfilename\fP De naam van het XML-bestand\&. 
.br
\fIos\fP De stream waarnaar de output geschreven wordt (nodig voor de exporter)\&.
.RE
.PP
REQUIRE(this->properlyInitialised, 'De parser was niet geinitialiseerd bij het aanroepen van setupStations\&.');
.br
REQUIRE(metro\&.properlyInitialised, 'Het metronet was niet geinitialiseerd bij het aanroepen van setupStations\&.');
.br


.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
