.TH "/home/jonathan/Desktop/Project Software Engineering/Metronet/PSE/src/Parser.h" 3 "Fri Apr 28 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jonathan/Desktop/Project Software Engineering/Metronet/PSE/src/Parser.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include 'Metronet\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBParser\fP"
.br
.RI "\fI\fBParser\fP klasse die het inlezen van XML-bestanden behandelt\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
