.TH "StatisticsMetronet" 3 "Fri Apr 28 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatisticsMetronet \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Statistics\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatisticsMetronet\fP ()"
.br
.ti -1c
.RI "bool \fBproperlyInitialised\fP () const "
.br
.ti -1c
.RI "double \fBgetTotaleOmzet\fP () const "
.br
.ti -1c
.RI "double \fBgetTotaleBezettingsgraad\fP () const "
.br
.ti -1c
.RI "int \fBgetAantalBezettePlaatsen\fP () const "
.br
.ti -1c
.RI "int \fBgetAantalZitplaatsen\fP () const "
.br
.ti -1c
.RI "int \fBgetPopLijn\fP () const "
.br
.ti -1c
.RI "int \fBgetNrAlba\fP () const "
.br
.ti -1c
.RI "int \fBgetNrPCC\fP () const "
.br
.ti -1c
.RI "void \fBsetTotaleOmzet\fP (double totaleOmzet)"
.br
.ti -1c
.RI "void \fBsetTotaleBezettingsgraad\fP (double totaleBezettingsgraad)"
.br
.ti -1c
.RI "void \fBsetAantalBezettePlaatsen\fP (int aantalBezettePlaatsen)"
.br
.ti -1c
.RI "void \fBsetAantalZitplaatsen\fP (int aantalZitplaatsen)"
.br
.ti -1c
.RI "void \fBsetPopLijn\fP (int popLijn)"
.br
.ti -1c
.RI "void \fBsetNrAlba\fP (int nrAlba)"
.br
.ti -1c
.RI "void \fBsetNrPCC\fP (int nrPCC)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StatisticsMetronet::StatisticsMetronet ()"

.SH "Member Function Documentation"
.PP 
.SS "int StatisticsMetronet::getAantalBezettePlaatsen () const"

.SS "int StatisticsMetronet::getAantalZitplaatsen () const"

.SS "int StatisticsMetronet::getNrAlba () const"

.SS "int StatisticsMetronet::getNrPCC () const"

.SS "int StatisticsMetronet::getPopLijn () const"

.SS "double StatisticsMetronet::getTotaleBezettingsgraad () const"

.SS "double StatisticsMetronet::getTotaleOmzet () const"

.SS "bool StatisticsMetronet::properlyInitialised () const"

.SS "void StatisticsMetronet::setAantalBezettePlaatsen (int aantalBezettePlaatsen)"

.SS "void StatisticsMetronet::setAantalZitplaatsen (int aantalZitplaatsen)"

.SS "void StatisticsMetronet::setNrAlba (int nrAlba)"

.SS "void StatisticsMetronet::setNrPCC (int nrPCC)"

.SS "void StatisticsMetronet::setPopLijn (int popLijn)"

.SS "void StatisticsMetronet::setTotaleBezettingsgraad (double totaleBezettingsgraad)"

.SS "void StatisticsMetronet::setTotaleOmzet (double totaleOmzet)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
