.TH "StatisticsStation" 3 "Fri Apr 28 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StatisticsStation \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Statistics\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStatisticsStation\fP ()"
.br
.ti -1c
.RI "bool \fBproperlyInitialised\fP () const "
.br
.ti -1c
.RI "int \fBgetAantalGroepen\fP () const "
.br
.ti -1c
.RI "int \fBgetAantalPersonen\fP () const "
.br
.ti -1c
.RI "void \fBsetAantalGroepen\fP (int aantalGroepen)"
.br
.ti -1c
.RI "void \fBsetAantalPersonen\fP (int aantalPersonen)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "StatisticsStation::StatisticsStation ()"

.SH "Member Function Documentation"
.PP 
.SS "int StatisticsStation::getAantalGroepen () const"

.SS "int StatisticsStation::getAantalPersonen () const"

.SS "bool StatisticsStation::properlyInitialised () const"

.SS "void StatisticsStation::setAantalGroepen (int aantalGroepen)"

.SS "void StatisticsStation::setAantalPersonen (int aantalPersonen)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
