.TH "Station" 3 "Thu Mar 16 2017" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Station \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Station\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStation\fP ()"
.br
.ti -1c
.RI "\fBStation\fP (std::string n, std::string vor, std::string volg, int sp, int op, int af)"
.br
.ti -1c
.RI "bool \fBproperlyInitialised\fP () const "
.br
.RI "\fIKijk na of de constructor in de juiste staat geeindigd is\&. \fP"
.ti -1c
.RI "std::string \fBgetNaam\fP () const "
.br
.RI "\fIGeef de naam terug van het station\&. \fP"
.ti -1c
.RI "std::string \fBgetVorige\fP () const "
.br
.RI "\fIGeef het vorig station terug\&. \fP"
.ti -1c
.RI "std::string \fBgetVolgende\fP () const "
.br
.RI "\fIGeef het volgende station\&. \fP"
.ti -1c
.RI "int \fBgetSpoor\fP () const "
.br
.RI "\fIGeef het spoor terug\&. \fP"
.ti -1c
.RI "int \fBgetOpstappen\fP () const "
.br
.RI "\fIGeef het aantal opstappende mensen terug\&. \fP"
.ti -1c
.RI "int \fBgetAfstappen\fP () const "
.br
.RI "\fIGeef het afstappende mensen terug\&. \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Station::Station ()"

.SS "Station::Station (std::string n, std::string vor, std::string volg, int sp, int op, int af)"

.SH "Member Function Documentation"
.PP 
.SS "int Station::getAfstappen () const"

.PP
Geef het afstappende mensen terug\&. 
.PP
\fBReturns:\fP
.RS 4
Een aantal afstappende mensen\&. REQUIRE(this->\fBproperlyInitialised()\fP, 'Station was niet geinitialiseerd bij de aanroep van getAfstappen\&.');
.br
.RE
.PP

.SS "std::string Station::getNaam () const"

.PP
Geef de naam terug van het station\&. 
.PP
\fBReturns:\fP
.RS 4
De naam van het station\&.
.RE
.PP
REQUIRE(this->\fBproperlyInitialised()\fP, 'Station was niet geinitialiseerd bij de aanroep van getNaam\&.');
.br

.SS "int Station::getOpstappen () const"

.PP
Geef het aantal opstappende mensen terug\&. 
.PP
\fBReturns:\fP
.RS 4
Een aantal opstappende mensen\&. REQUIRE(this->\fBproperlyInitialised()\fP, 'Station was niet geinitialiseerd bij de aanroep van getOpstappen\&.');
.br
.RE
.PP

.SS "int Station::getSpoor () const"

.PP
Geef het spoor terug\&. 
.PP
\fBReturns:\fP
.RS 4
Het spoor\&. REQUIRE(this->\fBproperlyInitialised()\fP, 'Station was niet geinitialiseerd bij de aanroep van getSpoor\&.');
.br
.RE
.PP

.SS "std::string Station::getVolgende () const"

.PP
Geef het volgende station\&. 
.PP
\fBReturns:\fP
.RS 4
Het volgende station\&.
.RE
.PP
REQUIRE(this->\fBproperlyInitialised()\fP, 'Station was niet geinitialiseerd bij de aanroep van getVolgende\&.');
.br

.SS "std::string Station::getVorige () const"

.PP
Geef het vorig station terug\&. 
.PP
\fBReturns:\fP
.RS 4
Het vorig station\&.
.RE
.PP
REQUIRE(this->\fBproperlyInitialised()\fP, 'Station was niet geinitialiseerd bij de aanroep van getVorige\&.');
.br

.SS "bool Station::properlyInitialised () const"

.PP
Kijk na of de constructor in de juiste staat geeindigd is\&. 
.PP
\fBReturns:\fP
.RS 4
Boolean die aangeeft of het object juist geinitialiseerd is\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
