.TH "Station" 3 "Wed Mar 22 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Station
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Station\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStation\fP ()"
.br
.ti -1c
.RI "\fBStation\fP (std::string n, std::string vor, std::string volg, int sp, int op, int af)"
.br
.ti -1c
.RI "bool \fBproperlyInitialised\fP () const"
.br
.RI "Kijk na of de constructor in de juiste staat geeindigd is\&. "
.ti -1c
.RI "std::string \fBgetNaam\fP () const"
.br
.RI "Geef de naam terug van het station\&. "
.ti -1c
.RI "std::string \fBgetVorige\fP () const"
.br
.RI "Geef het vorig station terug\&. "
.ti -1c
.RI "std::string \fBgetVolgende\fP () const"
.br
.RI "Geef het volgende station\&. "
.ti -1c
.RI "int \fBgetSpoor\fP () const"
.br
.RI "Geef het spoor terug\&. "
.ti -1c
.RI "int \fBgetOpstappen\fP () const"
.br
.RI "Geef het aantal opstappende mensen terug\&. "
.ti -1c
.RI "int \fBgetAfstappen\fP () const"
.br
.RI "Geef het afstappende mensen terug\&. "
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Station::Station ()"

.SS "Station::Station (std::string n, std::string vor, std::string volg, int sp, int op, int af)"

.SH "Member Function Documentation"
.PP 
.SS "int Station::getAfstappen () const"

.PP
Geef het afstappende mensen terug\&. 
.PP
\fBReturns:\fP
.RS 4
Een aantal afstappende mensen\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Station was niet geinitialiseerd bij de aanroep van getAfstappen\&.'); 
.RE
.PP

.SS "std::string Station::getNaam () const"

.PP
Geef de naam terug van het station\&. 
.PP
\fBReturns:\fP
.RS 4
De naam van het station\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Station was niet geinitialiseerd bij de aanroep van getNaam\&.'); 
.RE
.PP

.SS "int Station::getOpstappen () const"

.PP
Geef het aantal opstappende mensen terug\&. 
.PP
\fBReturns:\fP
.RS 4
Een aantal opstappende mensen\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Station was niet geinitialiseerd bij de aanroep van getOpstappen\&.'); 
.RE
.PP

.SS "int Station::getSpoor () const"

.PP
Geef het spoor terug\&. 
.PP
\fBReturns:\fP
.RS 4
Het spoor\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Station was niet geinitialiseerd bij de aanroep van getSpoor\&.'); 
.RE
.PP

.SS "std::string Station::getVolgende () const"

.PP
Geef het volgende station\&. 
.PP
\fBReturns:\fP
.RS 4
Het volgende station\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Station was niet geinitialiseerd bij de aanroep van getVolgende\&.'); 
.RE
.PP

.SS "std::string Station::getVorige () const"

.PP
Geef het vorig station terug\&. 
.PP
\fBReturns:\fP
.RS 4
Het vorig station\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Station was niet geinitialiseerd bij de aanroep van getVorige\&.'); 
.RE
.PP

.SS "bool Station::properlyInitialised () const"

.PP
Kijk na of de constructor in de juiste staat geeindigd is\&. 
.PP
\fBReturns:\fP
.RS 4
Boolean die aangeeft of het object juist geinitialiseerd is\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
