.TH "stationVerbinding" 3 "Fri Apr 28 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
stationVerbinding \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Station\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBvorige\fP"
.br
.ti -1c
.RI "std::string \fBvolgende\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "std::string stationVerbinding::volgende"

.SS "std::string stationVerbinding::vorige"


.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
