.TH "/home/jonathan/Desktop/Project Software Engineering/Metronet/PSE/src/tinyxmlparser.cpp" 3 "Thu Mar 9 2017" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jonathan/Desktop/Project Software Engineering/Metronet/PSE/src/tinyxmlparser.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <ctype\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br
\fC#include 'tinyxml\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTiXmlParsingData\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const unsigned char \fBTIXML_UTF_LEAD_0\fP = 0xefU"
.br
.ti -1c
.RI "const unsigned char \fBTIXML_UTF_LEAD_1\fP = 0xbbU"
.br
.ti -1c
.RI "const unsigned char \fBTIXML_UTF_LEAD_2\fP = 0xbfU"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const unsigned char TIXML_UTF_LEAD_0 = 0xefU"

.SS "const unsigned char TIXML_UTF_LEAD_1 = 0xbbU"

.SS "const unsigned char TIXML_UTF_LEAD_2 = 0xbfU"

.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
