.TH "/home/sergio/CLionProjects/SoftEng/src/tinyxml.cpp" 3 "Thu Mar 9 2017" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sergio/CLionProjects/SoftEng/src/tinyxml.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <ctype\&.h>\fP
.br
\fC#include 'tinyxml\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "FILE * \fBTiXmlFOpen\fP (const char *filename, const char *mode)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "FILE * TiXmlFOpen (const char * filename, const char * mode)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
