.TH "/home/sergio/CLionProjects/SoftEng/src/tinystr.cpp" 3 "Thu Mar 9 2017" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/sergio/CLionProjects/SoftEng/src/tinystr.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'tinystr\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTiXmlString\fP \fBoperator+\fP (const \fBTiXmlString\fP &a, const \fBTiXmlString\fP &b)"
.br
.ti -1c
.RI "\fBTiXmlString\fP \fBoperator+\fP (const \fBTiXmlString\fP &a, const char *b)"
.br
.ti -1c
.RI "\fBTiXmlString\fP \fBoperator+\fP (const char *a, const \fBTiXmlString\fP &b)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBTiXmlString\fP operator+ (const \fBTiXmlString\fP & a, const \fBTiXmlString\fP & b)"

.SS "\fBTiXmlString\fP operator+ (const \fBTiXmlString\fP & a, const char * b)"

.SS "\fBTiXmlString\fP operator+ (const char * a, const \fBTiXmlString\fP & b)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
