.TH "TiXmlAttributeSet" 3 "Thu Mar 9 2017" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TiXmlAttributeSet
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tinyxml\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTiXmlAttributeSet\fP ()"
.br
.ti -1c
.RI "\fB~TiXmlAttributeSet\fP ()"
.br
.ti -1c
.RI "void \fBAdd\fP (\fBTiXmlAttribute\fP *attribute)"
.br
.ti -1c
.RI "void \fBRemove\fP (\fBTiXmlAttribute\fP *attribute)"
.br
.ti -1c
.RI "const \fBTiXmlAttribute\fP * \fBFirst\fP () const"
.br
.ti -1c
.RI "\fBTiXmlAttribute\fP * \fBFirst\fP ()"
.br
.ti -1c
.RI "const \fBTiXmlAttribute\fP * \fBLast\fP () const"
.br
.ti -1c
.RI "\fBTiXmlAttribute\fP * \fBLast\fP ()"
.br
.ti -1c
.RI "\fBTiXmlAttribute\fP * \fBFind\fP (const char *_name) const"
.br
.ti -1c
.RI "\fBTiXmlAttribute\fP * \fBFindOrCreate\fP (const char *_name)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TiXmlAttributeSet::TiXmlAttributeSet ()"

.SS "TiXmlAttributeSet::~TiXmlAttributeSet ()"

.SH "Member Function Documentation"
.PP 
.SS "void TiXmlAttributeSet::Add (\fBTiXmlAttribute\fP * attribute)"

.SS "\fBTiXmlAttribute\fP * TiXmlAttributeSet::Find (const char * _name) const"

.SS "\fBTiXmlAttribute\fP * TiXmlAttributeSet::FindOrCreate (const char * _name)"

.SS "const \fBTiXmlAttribute\fP* TiXmlAttributeSet::First () const\fC [inline]\fP"

.SS "\fBTiXmlAttribute\fP* TiXmlAttributeSet::First ()\fC [inline]\fP"

.SS "const \fBTiXmlAttribute\fP* TiXmlAttributeSet::Last () const\fC [inline]\fP"

.SS "\fBTiXmlAttribute\fP* TiXmlAttributeSet::Last ()\fC [inline]\fP"

.SS "void TiXmlAttributeSet::Remove (\fBTiXmlAttribute\fP * attribute)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
