.TH "TiXmlOutStream" 3 "Thu Mar 9 2017" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TiXmlOutStream
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tinystr\&.h>\fP
.PP
Inherits \fBTiXmlString\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTiXmlOutStream\fP & \fBoperator<<\fP (const \fBTiXmlString\fP &in)"
.br
.ti -1c
.RI "\fBTiXmlOutStream\fP & \fBoperator<<\fP (const char *in)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "\fBTiXmlOutStream\fP& TiXmlOutStream::operator<< (const \fBTiXmlString\fP & in)\fC [inline]\fP"

.SS "\fBTiXmlOutStream\fP& TiXmlOutStream::operator<< (const char * in)\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
