.TH "TiXmlParsingData" 3 "Wed Mar 22 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TiXmlParsingData \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBStamp\fP (const char *now, \fBTiXmlEncoding\fP encoding)"
.br
.ti -1c
.RI "const \fBTiXmlCursor\fP & \fBCursor\fP () const "
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBTiXmlDocument\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "const \fBTiXmlCursor\fP& TiXmlParsingData::Cursor () const\fC [inline]\fP"

.SS "void TiXmlParsingData::Stamp (const char * now, \fBTiXmlEncoding\fP encoding)"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBTiXmlDocument\fP\fC [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
