.TH "/home/jonathan/Desktop/Project Software Engineering/Metronet/PSE/src/Tram.cpp" 3 "Fri Apr 28 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jonathan/Desktop/Project Software Engineering/Metronet/PSE/src/Tram.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Tram\&.h'\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "double \fBticketPrijs\fP = 2\&.0"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "double ticketPrijs = 2\&.0"

.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
