.TH "Tram" 3 "Wed Mar 22 2017" "Version 1.0" "Metronet" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Tram \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Tram\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTram\fP ()"
.br
.ti -1c
.RI "\fBTram\fP (int zit, int snel, int sp, std::string beginS)"
.br
.ti -1c
.RI "bool \fBproperlyInitialised\fP () const "
.br
.RI "\fIKijk na of de constructor in de juiste staat geeindigd is\&. \fP"
.ti -1c
.RI "int \fBgetZitplaatsen\fP () const "
.br
.RI "\fIGeef de zitplaatsen terug van de tram\&. \fP"
.ti -1c
.RI "int \fBgetPassagiers\fP () const "
.br
.RI "\fIGeef de passagiers terug van de tram\&. \fP"
.ti -1c
.RI "int \fBgetSnelheid\fP () const "
.br
.RI "\fIGeef de snelheid terug van de tram\&. \fP"
.ti -1c
.RI "int \fBgetSpoor\fP () const "
.br
.RI "\fIGeef het spoor terug\&. \fP"
.ti -1c
.RI "std::string \fBgetBeginStation\fP () const "
.br
.RI "\fIGeef het beginstation terug\&. \fP"
.ti -1c
.RI "std::string \fBgetHuidigStation\fP () const "
.br
.RI "\fIGeef het huidig station\&. \fP"
.ti -1c
.RI "void \fBsetHuidigStation\fP (std::string station)"
.br
.RI "\fIPast het huidige station aan\&. \fP"
.ti -1c
.RI "void \fBsetPassagiers\fP (int pas)"
.br
.RI "\fIPast het aantal passagiers aan\&. \fP"
.ti -1c
.RI "void \fBverplaatsTram\fP (std::string station, \fBExporter\fP *exp, std::ostream &os)"
.br
.RI "\fIVerplaatst een tram naar het opgegeven station\&. \fP"
.ti -1c
.RI "bool \fBafstappen\fP (int afstappen)"
.br
.RI "\fIEmuleert afstappen van passagiers\&. (Nieuw huidig aantal = huidig aantal - afstappende passagiers) \fP"
.ti -1c
.RI "bool \fBopstappen\fP (int opstappen)"
.br
.RI "\fIEmuleert opstappen van passagiers\&. (Nieuw huidig aantal = huidig aantal + opstappende passagiers) \fP"
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Tram::Tram ()"

.SS "Tram::Tram (int zit, int snel, int sp, std::string beginS)"

.SH "Member Function Documentation"
.PP 
.SS "bool Tram::afstappen (int afstappen)"

.PP
Emuleert afstappen van passagiers\&. (Nieuw huidig aantal = huidig aantal - afstappende passagiers) 
.PP
\fBParameters:\fP
.RS 4
\fIafstappen\fP Aantal passagiers dat afstapt\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean Of er meer passagiers afstapten dan mogelijk\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Tram was niet geinitialiseerd bij de aanroep van afstappen\&.'); 
.PP
REQUIRE(afstappen >= 0, 'Afstappen kan geen negatieve waarde hebben bij aanroep van afstappen\&.'); 
.RE
.PP

.SS "std::string Tram::getBeginStation () const"

.PP
Geef het beginstation terug\&. 
.PP
\fBReturns:\fP
.RS 4
Het beginstation\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Tram was niet geinitialiseerd bij de aanroep van getBeginStation\&.'); 
.RE
.PP

.SS "std::string Tram::getHuidigStation () const"

.PP
Geef het huidig station\&. 
.PP
\fBReturns:\fP
.RS 4
Het huidig station\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Tram was niet geinitialiseerd bij de aanroep van getHuidigStation\&.'); 
.RE
.PP

.SS "int Tram::getPassagiers () const"

.PP
Geef de passagiers terug van de tram\&. 
.PP
\fBReturns:\fP
.RS 4
De passagiers\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Tram was niet geinitialiseerd bij de aanroep van getPassagiers\&.'); 
.RE
.PP

.SS "int Tram::getSnelheid () const"

.PP
Geef de snelheid terug van de tram\&. 
.PP
\fBReturns:\fP
.RS 4
De snelheid\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Tram was niet geinitialiseerd bij de aanroep van getSnelheid\&.'); 
.RE
.PP

.SS "int Tram::getSpoor () const"

.PP
Geef het spoor terug\&. 
.PP
\fBReturns:\fP
.RS 4
Het spoor\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Tram was niet geinitialiseerd bij de aanroep van getSpoor\&.'); 
.RE
.PP

.SS "int Tram::getZitplaatsen () const"

.PP
Geef de zitplaatsen terug van de tram\&. 
.PP
\fBReturns:\fP
.RS 4
De zitplaatsen\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Tram was niet geinitialiseerd bij de aanroep van getZitplaatsen\&.'); 
.RE
.PP

.SS "bool Tram::opstappen (int opstappen)"

.PP
Emuleert opstappen van passagiers\&. (Nieuw huidig aantal = huidig aantal + opstappende passagiers) 
.PP
\fBParameters:\fP
.RS 4
\fIopstappen\fP Aantal passagiers dat opstapt\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean Of er meer passigiers opstapten dan mogelijk\&. 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Tram was niet geinitialiseerd bij de aanroep van opstappen\&.'); 
.PP
REQUIRE(opstappen >= 0, 'Opstappen kan geen negatieve waarde hebben bij aanroep van opstappen\&.'); 
.RE
.PP

.SS "bool Tram::properlyInitialised () const"

.PP
Kijk na of de constructor in de juiste staat geeindigd is\&. 
.PP
\fBReturns:\fP
.RS 4
Boolean die aangeeft of het object juist geinitialiseerd is\&. 
.RE
.PP

.SS "void Tram::setHuidigStation (std::string station)"

.PP
Past het huidige station aan\&. 
.PP
\fBParameters:\fP
.RS 4
\fIstation\fP Nieuw huidig station 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Tram was niet geinitialiseerd bij de aanroep van getHuidigStation\&.'); 
.RE
.PP
\fBPostcondition:\fP
.RS 4
ENSURE((huidigStation == station), 'huidigStation is niet aangepast door setHuidigStation\&.'); 
.RE
.PP

.SS "void Tram::setPassagiers (int pas)"

.PP
Past het aantal passagiers aan\&. 
.PP
\fBParameters:\fP
.RS 4
\fIpas\fP Positief nieuw aantal passagiers 
.RE
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Tram was niet geinitialiseerd bij de aanroep van setPassagiers\&.'); 
.PP
REQUIRE(passagiers >= 0, 'Aantal passagiers moet positief zijn\&.'); 
.RE
.PP
\fBPostcondition:\fP
.RS 4
ENSURE((passagiers == pas), 'Aantal passagiers niet aangepast bij aanroep van setPassagiers\&.'); 
.RE
.PP

.SS "void Tram::verplaatsTram (std::string station, \fBExporter\fP * exp, std::ostream & os)"

.PP
Verplaatst een tram naar het opgegeven station\&. 
.PP
\fBPrecondition:\fP
.RS 4
REQUIRE(this->\fBproperlyInitialised()\fP, 'Tram was niet geinitialiseerd bij de aanroep van verplaatsTram\&.'); 
.RE
.PP
\fBPostcondition:\fP
.RS 4
ENSURE((huidigStation == station), 'huidigStation is niet correct aangepast\&.'); 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Metronet from the source code\&.
